### ISSUE TITLE
v1.22 Makes the Tray Indicator Go Away

### ISSUE THREAD

**Issue by bourretbrandon** [linuxmint/nvidia-prime-applet#4]
I'm on Mint 20 Cinnamon, 5.4.0-42, all appropriate "libappindicator" stuff installed, and all my other tray apps/icons are working fine. When I updated nvidia-prime-applet from v1.21 to v1.22, the tray icon disappears. Even when opening nvidia-settings and trying to enable the tray icon, it does nothing. When I downgrade back to v1.21, the icon comes back. Regression?

**Comment by ASparkOfFire** [comment]
@bourretbrandon Strange, did you try executing from the terminal? _**(/usr/lib/nvidia-prime-applet/nvidia-prime)**_

**Comment by bourretbrandon** [comment]
No, I didn't try that command from the terminal (....../nvidia-prime).

When I try to run pip3, the return is "command not found". I haven't tinkered with the default out-of-the-box Python install between v1.21 and v1.22. No Python has been added/removed from the installation.

I went back to v1.21 for now. But I'll try v1.22 again and try that "nvidia-prime" command. If it works, that's great. But it would mean I have to manually add that to the "startup" apps. Which I don't have to do with v1.21. I'll keep you updated.

**Comment by bourretbrandon** [comment]
@ASparkOfFire You're definitely right about the Python "packaging" dependency.

$ /usr/lib/nvidia-prime-applet/nvidia-prime
Traceback (most recent call last):
  File "/usr/lib/nvidia-prime-applet/nvidia-prime", line 7, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'


The missing dependency is "python3-pip 20.0.2-5ubuntu1" (and its dependencies). All is well now. But isn't there a way to have this dependency resolved during installation? If I had the issue, I'm sure others have as well.

Thank you for your help getting it solved.

**Comment by Leopard1907** [comment]
Same issue here. Prime applet only becomes visible if i execute `/usr/lib/nvidia-prime-applet/nvidia-prime`from terminal.

**Comment by ASparkOfFire** [comment]
> @ASparkOfFire You're definitely right about the Python "packaging" dependency.
> 
> $ /usr/lib/nvidia-prime-applet/nvidia-prime
> Traceback (most recent call last):
> File "/usr/lib/nvidia-prime-applet/nvidia-prime", line 7, in
> from packaging import version
> ModuleNotFoundError: No module named 'packaging'
> 
> The missing dependency is "python3-pip 20.0.2-5ubuntu1" (and its dependencies). All is well now. But isn't there a way to have this dependency resolved during installation? If I had the issue, I'm sure others have as well.
> 
> Thank you for your help getting it solved.

My Pleasure, I hope developers fix it soon. :octocat:
